# Generated by Django 5.1.1 on 2024-10-17 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 10, 17, 8, 13, 15, 644424, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
